import React from 'react'
import './PictureExample.css'
import SampleImage1 from '../../assets/img1.jpg'
import SampleImage2 from '../../assets/img2.jpg'
import SampleImage3 from '../../assets/img3.jpg'

const PictureExample = () => {
  return (
    <div className="pictureExamle">
        <p>Presented here are a selection of example images generated by this AI.</p>
        <div className="sampleImages">
            <img src={SampleImage1} alt="Sample Image 1" />
            <img src={SampleImage2} alt="Sample Image 2" />
            <img src={SampleImage3} alt="Sample Image 3" />
        </div>
    </div>
  )
}

export default PictureExample